### ISSUE TITLE
Syntax Error: Unexpected token: punc(() during rollup step

### ISSUE THREAD

**Issue by mweinelt** [RomRider/apexcharts-card#107]
**Checklist**
- [x] I updated the card to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I verified that I'm really running the lastest version in my browser console
- [x] I checked if there is another issue opened with the same problem

**Describe the bug**
Trying to build this project from source (`npm run build`) fails for me during the rollup step with 

```
> apexcharts-card@1.7.1 build /nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card
> npm run build:types-check && npm run lint && npm run rollup


> apexcharts-card@1.7.1 build:types-check /nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card
> ts-interface-builder src/types-config.ts


> apexcharts-card@1.7.1 lint /nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card
> eslint src/*.ts


> apexcharts-card@1.7.1 rollup /nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card
> rollup -c


src/apexcharts-card.ts → ./dist...
  3198 | };
  3199 |
> 3200 | function(){try{(new Date).toLocaleDateString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleDateString(t,{year:"numeric",month:"long",day:"numeric"})}:function(t){return fecha.format(t,"mediumDate")};function(){try{(new Date).toLocaleString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleString(t,{year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"haDateTime")};function(){try{(new Date).toLocaleTimeString("i");}catch(e){return "RangeError"===e.name}return !1}()?function(e,t){return e.toLocaleTimeString(t,{hour:"numeric",minute:"2-digit"})}:function(t){return fecha.format(t,"shortTime")};var X=function(){var e=document.querySelector("home-assistant");if(e=(e=(e=(e=(e=(e=(e=(e=e&&e.shadowRoot)&&e.querySelector("home-assistant-main"))&&e.shadowRoot)&&e.querySelector("app-drawer-layout partial-panel-resolver"))&&e.shadowRoot||e)&&e.querySelector("ha-panel-lovelace"))&&e.shadowRoot)&&e.querySelector("hui-root")){var t=e.lovelace;return t.current_view=e.___curView,t}return null};
       |        ^ Unexpected token: punc (()
  3201 |
  3202 | var commonjsGlobal = typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};
  3203 |
[!] (plugin terser) SyntaxError: Unexpected token: punc (()
SyntaxError: Unexpected token: punc (()
    at js_error (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:548:11)
    at croak (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1272:9)
    at token_error (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1280:9)
    at unexpected (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1286:9)
    at function_ (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1718:17)
    at statement (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1467:24)
    at _embed_tokens_wrapper (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:1337:26)
    at parse_toplevel (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:3486:23)
    at parse (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:3498:7)
    at minify (/nix/store/sl25gdgszmdbps1imwy87y0pipbxlcjr-node_apexcharts-card-1.7.1/lib/node_modules/apexcharts-card/node_modules/terser/dist/bundle.min.js:26486:38)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apexcharts-card@1.7.1 rollup: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apexcharts-card@1.7.1 rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-03-01T03_03_02_532Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apexcharts-card@1.7.1 build: `npm run build:types-check && npm run lint && npm run rollup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apexcharts-card@1.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Version of the card**
Version: 1.7.1

**To Reproduce**
This is the configuration I used:
```yaml
# n/a
```

**Expected behavior**
Running `npm run build` should create the compiled/bundled/minified module.

**Additional context**
I'm trying to package this up for NixOS using node2nix (https://github.com/svanderburg/node2nix).

**Comment by RomRider** [comment]
All the builds work since the beginning, so I'm not sure what you are doing.
I'm using `npm ci` instead of `npm install` to install the dependencies if that helps. Revert your package-lock.json and remove your `node_modules` before running `npm ci`.

**Comment by mweinelt** [comment]
Looks like I'm running into a terser issue: https://github.com/terser/terser/issues/540

**Comment by RomRider** [comment]
I don't have this issue so it seems related to the conversion you are trying to achieve.
